- host: webservers
  become: true
  tasks:
    - name: Check Apache Status on Ubuntu
      ansible.builtin.service:
        name: apache2
        state: started
      register: apache_status
      check_mode: true
      when: ansible_distribution == "Ubuntu"
    - name: debug
      ansible.builtin.debug:
        msg: >-
          Apache2 service is {{ apache_status.changed |
          ternary('stopped','started') }}
    - name: Copy default html file for site
      tags: 'apache,apache2,httpd'
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 420
      when: apache_status.changed

- host: 'webserver1, webserver2'
  become: true
  tasks:
    - name: Copy file from remote machines to local.
      fetch:
        src: /var/log/apache2/access.log
        dest: /tmp/fetched
      when: ansible_distribution == "Ubuntu"
