---

- hosts: all
  become: true
  tasks:

  # Play or Task

  - name: Install apache and php
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

