---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  # Play or Task for Ubuntu

  - name: Install apache2 and php packages for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  # Play or Task for CentOS

  - name: Update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install apache httpd and php packages for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
