---

- hosts: all
  become: true
  tasks:

  # Play or Task for Ubuntu

  - name: Install apache2 and php packages for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  # Play or Task for CentOS

  - name: Install apache httpd and php packages for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

