- name: Install mariadb package (Ubuntu)
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install mariadb package (CentOS)
  tags: db,mariadb,centos
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"
